name: flutterStudy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  fluttertoast: ^4.0.0         # https://github.com/PonnamKarthik/FlutterToast  toast 组件
  date_format: ^1.0.8
  flutter_cupertino_date_picker: 
    git:
      url: https://github.com/imshashank/flutter-cupertino-date-picker # Repo
      ref: master # Branch name
                                      # https://github.com/dylanwuzh/flutter-cupertino-date-picker 日期组件
  flutter_swiper : ^1.1.6 # https://github.com/best-flutter/flutter_swiper  轮播图
  waterfall_flow: ^2.0.2   #https://github.com/fluttercandies/waterfall_flow 瀑布流
  loading_more_list: ^3.0.0
  pull_to_refresh: ^1.6.0  #https://github.com/peng8350/flutter_pulltorefresh 下拉刷新
  dio: ^3.0.9 #https://github.com/flutterchina/dio/blob/master/README-ZH.md
  flutter_webview_plugin: ^0.3.11 #https://pub.dev/packages/flutter_webview_plugin  应用webview
  qr_flutter: ^3.2.0  #https://github.com/lukef/qr.flutter                     生成二维码
  barcode_scan: ^3.0.1 #https://github.com/mintware-de/flutter_barcode_reader  扫描解析二维码
  provider: ^4.3.1  #处理父子组件之间的状态管理
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any  
  flutter_driver:
    sdk: flutter
  mockito: ^4.1.0  # https://github.com/dart-lang/mockito  测试用
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/drawerhead.jpeg
     - assets/images/head.jpg
     - assets/images/cat.png
     - assets/images/rabit.png
     - assets/images/swiper1.jpg
     - assets/images/swiper2.jpg
     - assets/images/swiper3.jpg
     - assets/images/swiper4.jpg
     - assets/images/pic1.jpg
     - assets/images/pic2.jpg
     - assets/images/pic3.jpg
     - assets/images/pic4.jpg
     - assets/images/tou1.jpg
     - assets/images/tou2.jpg
     - assets/images/tou3.jpg
     - assets/images/tou4.jpg
     - assets/images/tou5.jpg
     - assets/images/tou6.jpg
     - assets/images/tou7.jpg
     - assets/images/tou8.jpg
     - assets/images/tou9.jpg
     - assets/images/tou10.jpg
     - assets/images/xinxing.png
     - assets/data/users.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
